# Generated by Django 6.0.5 on 2026-06-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=20)),
                ('cuerpo', models.TextField(blank=True, null=True)),
                ('url_video', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_destacada', models.CharField(max_length=255)),
                ('fuente', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_noticia', models.DateField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('acceso_limitado', models.BooleanField(default=False)),
                ('estado', models.CharField(default='Borrador', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'noticias',
            },
        ),
    ]
