# Generated by Django 6.0.5 on 2026-05-30 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteActividad',
            fields=[
                ('id_reporte_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(max_length=100)),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
