# Generated by Django 6.0.5 on 2026-06-02 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Especialidad',
            },
        ),
        migrations.CreateModel(
            name='ServicioGeneral',
            fields=[
                ('id_servicio_general', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ServicioGeneral',
            },
        ),
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('id_veterinaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clinica', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=12)),
                ('correo_publico', models.CharField(blank=True, max_length=100, null=True)),
                ('horario_atencion', models.CharField(blank=True, max_length=150, null=True)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Veterinaria',
            },
        ),
        migrations.CreateModel(
            name='ServicioVeterinaria',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_veterinaria', models.ForeignKey(db_column='id_veterinaria', on_delete=django.db.models.deletion.CASCADE, to='api.veterinaria')),
            ],
            options={
                'db_table': 'ServicioVeterinaria',
            },
        ),
        migrations.CreateModel(
            name='ResenaVeterinaria',
            fields=[
                ('id_resena', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('calificacion', models.IntegerField()),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_veterinaria', models.ForeignKey(db_column='id_veterinaria', on_delete=django.db.models.deletion.CASCADE, to='api.veterinaria')),
            ],
            options={
                'db_table': 'ResenaVeterinaria',
            },
        ),
        migrations.CreateModel(
            name='ProductoVeterinaria',
            fields=[
                ('id_producto_vet', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_veterinaria', models.ForeignKey(db_column='id_veterinaria', on_delete=django.db.models.deletion.CASCADE, to='api.veterinaria')),
            ],
            options={
                'db_table': 'ProductoVeterinaria',
            },
        ),
        migrations.CreateModel(
            name='VeterinariaEspecialidad',
            fields=[
                ('id_vet_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_especialidad', models.ForeignKey(db_column='id_especialidad', on_delete=django.db.models.deletion.RESTRICT, to='api.especialidad')),
                ('id_veterinaria', models.ForeignKey(db_column='id_veterinaria', on_delete=django.db.models.deletion.CASCADE, to='api.veterinaria')),
            ],
            options={
                'db_table': 'tr_VeterinariaEspecialidad',
                'unique_together': {('id_veterinaria', 'id_especialidad')},
            },
        ),
        migrations.CreateModel(
            name='VeterinariaServicio',
            fields=[
                ('id_vet_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_servicio_general', models.ForeignKey(db_column='id_servicio_general', on_delete=django.db.models.deletion.RESTRICT, to='api.serviciogeneral')),
                ('id_veterinaria', models.ForeignKey(db_column='id_veterinaria', on_delete=django.db.models.deletion.CASCADE, to='api.veterinaria')),
            ],
            options={
                'db_table': 'tr_VeterinariaServicio',
                'unique_together': {('id_veterinaria', 'id_servicio_general')},
            },
        ),
    ]
