# Generated by Django 6.0.5 on 2026-05-30 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoriapreguntas',
            fields=[
                ('id_categoria_preguntas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categoriapreguntas',
            },
        ),
        migrations.CreateModel(
            name='preguntafrecuente',
            fields=[
                ('id_faq', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('id_categoria_faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriapreguntas')),
            ],
            options={
                'db_table': 'preguntafrecuente',
            },
        ),
    ]
